#
# Copyright (c) 2009-2010 Nokia Corporation and/or its subsidiary(-ies).
# All rights reserved.
# This component and the accompanying materials are made available
# under the terms of "Eclipse Public License v1.0"
# which accompanies this distribution, and is available
# at the URL "http://www.eclipse.org/legal/epl-v10.html".
#
# Initial Contributors:
# Nokia Corporation - initial contribution.
#
# Contributors:
#
# Description:
#
# Domain String table for test domain names
fstringtable DOMAINSTRINGS
# Internal Stings
EDomain1 www.domain1.com
EDomain2 www.domain2.com
EDomain3 www.domain3.com
EDomain4 www.domain4.com
EDomain5 www.domain5.com
EDomain6 www.domain6.com
EDomain7 www.domain7.com
EDomain8 www.domain8.com
EDomain9 www.domain9.com
EDomain10 www.domain10.com
EDomain11 www.domain11.com
EDomain12 www.domain12.com
EDomain13 www.domain13.com
EDomain14 www.domain14.com
EDomain15 www.domain15.com
EDomain16 www.domain16.com
EDomain17 www.domain17.com
EDomain18 www.domain18.com
EDomain19 www.domain19.com
EDomain20 www.domain20.com
EDomain21 www.domain21.com
EDomain22 www.domain22.com
EDomain23 www.domain23.com
EDomain24 www.domain24.com
EDomain25 www.domain25.com
EDomain26 www.domain26.com
EDomain27 www.domain27.com
EDomain28 www.domain28.com
EDomain29 www.domain29.com
EDomain30 www.domain30.com
