// Created by TraceCompiler 1.3.1
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __HARVESTERSERVERSESSIONTRACES_H__
#define __HARVESTERSERVERSESSIONTRACES_H__

#define KOstTraceComponentID 0x200009f5

#define CHARVESTERSERVERSESSION_NEWL 0x300bd
#define CHARVESTERSERVERSESSION_NEWLC 0x300be
#define CHARVESTERSERVERSESSION_CONSTRUCTL 0x300bf
#define CHARVESTERSERVERSESSION_CHARVESTERSERVERSESSION 0x300c0
#define DUP1_CHARVESTERSERVERSESSION_CHARVESTERSERVERSESSION 0x300c1
#define CHARVESTERSERVERSESSION_SERVICEL 0x300c2
#define CHARVESTERSERVERSESSION_DISCONNECT 0x300c3


#endif

// End of file

