#
# Copyright (c) 2009-2010 Nokia Corporation and/or its subsidiary(-ies).
# All rights reserved.
# This component and the accompanying materials are made available
# under the terms of "Eclipse Public License v1.0"
# which accompanies this distribution, and is available
# at the URL "http://www.eclipse.org/legal/epl-v10.html".
#
# Initial Contributors:
# Nokia Corporation - initial contribution.
#
# Contributors:
#
# Description:
#
# Security Policy Plug-in, named properties string table
stringtable SecurityPolicyProperties
#
# Standard token values, enumerations or parameters
#
ESequenceNumberMode _snm
EKeyRefreshRate _krr
ESharedSecret _ss
ERecordLengthUsage _rlu
EAnonymousAllowed _aa
#
# Values for sequence number mode
ENotUsed _nu 
EImplicit _im
EExplicit _ex
#
# Values for 'record length usage' ('not used' value is taken from above)
EUsed _u
#
# Values for 'anonymous allowed'
EAllowed _allowed
ENotAllowed _na
