#
# Copyright (c) 2009-2010 Nokia Corporation and/or its subsidiary(-ies).
# All rights reserved.
# This component and the accompanying materials are made available
# under the terms of "Eclipse Public License v1.0"
# which accompanies this distribution, and is available
# at the URL "http://www.eclipse.org/legal/epl-v10.html".
#
# Initial Contributors:
# Nokia Corporation - initial contribution.
#
# Contributors:
#
# Description:
#
# WSP String table
fstringtable WSPCharacterSets
#
# The character sets supported in the WSP encoding
#
EBig5 big5
EIso10646ucs2 iso-10646-ucs-2
EIso88591 iso-8859-1
EIso88592 iso-8859-2
EIso88593 iso-8859-3
EIso88594 iso-8859-4
EIso88595 iso-8859-5
EIso88596 iso-8859-6
EIso88597 iso-8859-7
EIso88598 iso-8859-8
EIso88599 iso-8859-9
EShiftJIS shift_JIS
EUsAscii us-ascii
EUtf8 utf-8
EGsmDefaultAlphabet gsm-default-alphabet