#
# Copyright (c) 2009-2010 Nokia Corporation and/or its subsidiary(-ies).
# All rights reserved.
# This component and the accompanying materials are made available
# under the terms of "Eclipse Public License v1.0"
# which accompanies this distribution, and is available
# at the URL "http://www.eclipse.org/legal/epl-v10.html".
#
# Initial Contributors:
# Nokia Corporation - initial contribution.
#
# Contributors:
#
# Description:
#
# WSP String table
fstringtable WSPLanguages
#
# Language assignments
#
EAnyLanguage *
EAfar aa
EAbkhazian ab
EAfrikaans af
EAmharic am
EArabic ar
EAssamese as
EAymara ay
EAzerbaijani az
EBashkir ba
EByelorussian be
EBulgarian bg
EBihari bh
EBislama bi
EBengaliBangla bn
ETibetan bo
EBreton br
ECatalan ca
ECorsican co
ECzech cs
EWelsh cy
EDanish da
EGerman de
EBhutani dz
EGreek el
EEnglish en
EEsperanto eo
ESpanish es
EEstonian et
EBasque eu
EPersian fa
EFinnish fi
EFiji fj
EUrdu ur
EFrench fr
EUzbek uz
EIrish ga
EScotsGaelic gd
EGalician gl
EGuarani gn
EGujarati gu
EHausa ha
EHebrew he
EHindi hi
ECroatian hr
EHungarian hu
EArmenian hy
EVietnamese vi
EIndonesian id
EWolof wo
EXhosa xh
EIcelandic is
EItalian it
EYoruba yo
EJapanese ja
EJavanese jw
EGeorgian ka
EKazakh kk
EZhuang za
ECambodian km
EKannada kn
EKorean ko
EKashmiri ks
EKurdish ku
EKirghiz ky
EChinese zh
ELingala ln
ELaothian lo
ELithuanian lt
ELatvianLettish lv
EMalagasy mg
EMaori mi
EMacedonian mk
EMalayalam ml
EMongolian mn
EMoldavian mo
EMarathi mr
EMalay ms
EMaltese mt
EBurmese my
EUkrainian uk
ENepali ne
EDutch nl
ENorwegian no
EOccitan oc
EOromo om
EOriya or
EPunjabi pa
EPolish po
EPashtoPushto ps
EPortuguese pt
EQuechua qu
EZulu zu
EKirundi rn
ERomanian ro
ERussian ru
EKinyarwanda rw
ESanskrit sa
ESindhi sd
ESangho sg
ESerbo-Croatian sh
ESinhalese si
ESlovak sk
ESlovenian sl
ESamoan sm
EShona sn
ESomali so
EAlbanian sq
ESerbian sr
ESiswati ss
ESesotho st
ESundanese su
ESwedish sv
ESwahili sw
ETamil ta
ETelugu te
ETajik tg
EThai th
ETigrinya ti
ETurkmen tk
ETagalog tl
ESetswana tn
ETonga to
ETurkish tr
ETsonga ts
ETatar tt
ETwi tw
EUighur ug
ENauru na
EFaeroese fo
EFrisian fy
EInterlingua ia
EVolapuk vo
EInterlingue ie
EInupiak ik
EYiddish yi
EInuktitut iu
EGreenlandic kl
ELatin la
ERhaeto-Romance rm