#
# Copyright (c) 2009-2010 Nokia Corporation and/or its subsidiary(-ies).
# All rights reserved.
# This component and the accompanying materials are made available
# under the terms of "Eclipse Public License v1.0"
# which accompanies this distribution, and is available
# at the URL "http://www.eclipse.org/legal/epl-v10.html".
#
# Initial Contributors:
# Nokia Corporation - initial contribution.
#
# Contributors:
#
# Description:
#
# WSP String table
fstringtable WSPStdConstants
#
# Standard token values, enumerations or parameters
#
EAny *
EClose Close
ENoCache No-cache
ENoStore No-store
EMaxAge Max-age
EMaxStale Max-stale
EOnlyIfCached Only-if-cached
EPrivate Private
EPublic Public
ENoTransform No-transform
EMustRevalidate Must-revalidate
EProxyRevalidate Must-revalidate
EChunked Chunked
EBasic Basic
EMinFresh Min-fresh
ESMaxage S-maxage
EGzip Gzip
ECompress Compress
EDeflate Deflate
ENone None
EBytes Bytes
ETrailers Trailers
EIdentity Identity
EByteRange Byte-range
ESuffixByteRange Suffix-byte-range
E100Continue 100-continue
EWspVersion11 1.1
EWspVersion12 1.2
EWspVersion13 1.3
EWspVersion14 1.4
