//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
// Preliminary steps for running the security tests

LOAD_SUITE TestBookmarksServer_Cap -SharedData

// General Steps

RUN_TEST_STEP 	100 	 TestBookmarksServer_Cap	TestDeleteFolderStep		c:\testdata\ini\TestBookmarksSuite.ini 	MainFolder

RUN_TEST_STEP 	100 	 TestBookmarksServer_Cap	TestCreateBookmarkItemsStep 	c:\testdata\ini\TestBookmarksSuite.ini 	MainFolder
RUN_TEST_STEP 	100 	 TestBookmarksServer_Cap	TestCreateBookmarkItemsStep 	c:\testdata\ini\TestBookmarksSuite.ini 	Folder1
RUN_TEST_STEP 	100 	 TestBookmarksServer_Cap	TestCreateBookmarkItemsStep 	c:\testdata\ini\TestBookmarksSuite.ini 	Folder2
RUN_TEST_STEP 	100 	 TestBookmarksServer_Cap	TestCreateBookmarkItemsStep 	c:\testdata\ini\TestBookmarksSuite.ini 	Bookmark1
RUN_TEST_STEP 	100 	 TestBookmarksServer_Cap	TestCreateBookmarkItemsStep 	c:\testdata\ini\TestBookmarksSuite.ini 	Bookmark2

RUN_TEST_STEP 	100 	 TestBookmarksServer_Cap	TestSetPropertyStep 		c:\testdata\ini\TestBookmarksSuite.ini 	Bookmark1_SetTitle
RUN_TEST_STEP 	100 	 TestBookmarksServer_Cap	TestSetPropertyStep 		c:\testdata\ini\TestBookmarksSuite.ini 	Bookmark2_SetTitle

RUN_TEST_STEP 	100 	 TestBookmarksServer_Cap	TestSetPropertyStep 		c:\testdata\ini\TestBookmarksSuite_Security.ini 	Folder1_SetPrivate
RUN_TEST_STEP 	100 	 TestBookmarksServer_Cap	TestSetPropertyStep 		c:\testdata\ini\TestBookmarksSuite_Security.ini 	Bookmark2_SetPrivate

RUN_TEST_STEP 	100 	 TestBookmarksServer_Cap	TestSetPropertyStep 		c:\testdata\ini\TestBookmarksSuite.ini 	Folder1_SetWriteable_False
RUN_TEST_STEP 	100 	 TestBookmarksServer_Cap	TestSetPropertyStep 		c:\testdata\ini\TestBookmarksSuite.ini 	Bookmark1_SetWriteable_False

// For Test Case 4.49 in Cap_00018000_TestBookmarksScript
RUN_TEST_STEP 	100 	 TestBookmarksServer_Cap	TestCreateBookmarkItemsStep 	c:\testdata\ini\TestBookmarksSuite.ini 	Folder4
RUN_TEST_STEP 	100 	 TestBookmarksServer_Cap	TestSetPropertyStep 		c:\testdata\ini\TestBookmarksSuite.ini 	Folder4_SetWriteable_False

// For Test Case 4.41 in Cap_00008000_TestBookmarksScript
RUN_TEST_STEP 	100 	 TestBookmarksServer_Cap	TestSetPropertyStep 		c:\testdata\ini\TestBookmarksSuite.ini 	Folder2_SetDescription