//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//! @file
//! @SYMTestCaseID MSG-FRAMEWORK-0243
//! @SYMTestType UT
//! @SYMTestPriority High
//! @SYMPREQ 234
//! @SYMDEF T_SORT_UTCServer.exe
//! @SYMTestCaseDesc Each test case tests for correct parsing of date header information by the IMAP system.
//! @SYMTestActions Connects to the dummy IMAP server using loop back address, syncs known email.
//! @SYMTestExpectedResults The dates used to time-stamp message store entries must be as expected.

PRINT Run all T_UTC_SORTServer Tests 
LOAD_SUITE T_SORT_UTCServer -SharedData
START_TESTCASE 1
RUN_TEST_STEP 1000 T_SORT_UTCServer TestUTCSort
END_TESTCASE 1
