#
# Copyright (c) 2006-2009 Nokia Corporation and/or its subsidiary(-ies).
# All rights reserved.
# This component and the accompanying materials are made available
# under the terms of "Eclipse Public License v1.0"
# which accompanies this distribution, and is available
# at the URL "http://www.eclipse.org/legal/epl-v10.html".
#
# Initial Contributors:
# Nokia Corporation - initial contribution.
#
# Contributors:
#
# Description:
#
stringtable DRMStringDict00TagTable
# //////////////////////////////////////////////////////////////////////
!// Element names
!// CodePage 00
ERights		o-ex:rights
EContext	o-ex:context
EVersion	o-dd:version
EUid		o-dd:uid
EAgreement	o-ex:agreement
EAsset		o-ex:asset
EKeyInfo	ds:KeyInfo
EKeyValue	ds:KeyValue
EPermission	o-ex:permission
EPlay		o-dd:play
EDisplay	o-dd:display
EExecute	o-dd:execute
EPrint		o-dd:print
EConstraint	o-ex:constraint
ECount		o-dd:count
EDateTime	o-dd:datetime
EStart		o-dd:start
EEnd		o-dd:end
EInterval	o-dd:interval
# //////////////////////////////////////////////////////////////////////
!// For XML
EUri						-//OMA//DTD DRMREL 1.0//EN
!// For WBXML
EPublicId					14~0
EFormalPublicId				-//OMA//DTD DRMREL 1.0//EN~0