#
# Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies). 
# All rights reserved.
# This component and the accompanying materials are made available
# under the terms of "Eclipse Public License v1.0"
# which accompanies this distribution, and is available
# at the URL "http://www.eclipse.org/legal/epl-v10.html".
#
# Initial Contributors:
# Nokia Corporation - initial contribution.
#
# Contributors:
# 
# Description: S60 makefile_templates level configuration makefile
#

 
MAKEFILE = /sf/mw/platformtools/gfxconversion/mifconv/makefile_templates/makefile

 
# Place the first target as the default target which is executed from this level 

export_template_files :: template_makefiles
          
include include_template.mk 
