/**
* Copyright (c) 1999-2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
*
*/



/**
 @file TelDebug.h
 @internalComponent
*/

#ifndef _TELDEBUG_H_
#define _TELDEBUG_H_

#include <comms-infras/commsdebugutility.h>
#include <e32base.h>


/**
@internalComponent
*/
_LIT8(KTelnetLoggingCompnt,"Telnet");
_LIT8(KTelnetLoggingTag,"Teldebug");


#endif //_TELDEBUG_H_

