// Created by TraceCompiler 1.3.1
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __HARVESTERCLIENTAOTRACES_H__
#define __HARVESTERCLIENTAOTRACES_H__

#define KOstTraceComponentID 0x200009f4

#define CHARVESTERCLIENTAO_NEWL 0x3000d
#define CHARVESTERCLIENTAO_CHARVESTERCLIENTAO 0x3000e
#define DUP1_CHARVESTERCLIENTAO_CHARVESTERCLIENTAO 0x3000f
#define CHARVESTERCLIENTAO_CONSTRUCTL 0x30010
#define CHARVESTERCLIENTAO_SETOBSERVER 0x30011
#define CHARVESTERCLIENTAO_DOCANCEL 0x30013
#define CHARVESTERCLIENTAO_RUNL 0x30014
#define CHARVESTERCLIENTAO_REMOVEOBSERVER 0x30015


#endif

// End of file

