// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
//! @file			tld_config_duplicate_test.script
//
// Description:
// @internalAll

PRINT Running_TLD_Functionality_Test

// Load the test
LOAD_SUITE	TestWListBListUriServer
LOAD_SUITE	systemtest_security

START_TESTCASE                IWS-WLBL-TLD-CIT-POS-0001-0001
//! @SYMTestCaseID              IWS-WLBL-TLD-CIT-POS-0001-0001
//! @SYMTestCaseDesc            Test the Pre-configuration of TLD Policy file functionality.
//!                             The Policy data in the pre-configuration file should be added to database when loaded first time.
//!                             The pre-configuration file in XML format contains white/Black listed characters against each TLD.
//!								Install c:\testdata\sisupgrade\ineturilist_duplicate.SIS
//! @SYMTestPriority            Critical
//! @SYMTestCaseDependencies	setup_st-sanity-security.script
//! @SYMTestActions             1. Place the pre-configuration file which contains Policy data in corresponding directory.
//!                             2. This Policy file should be read and added to the database when database is initialised by the InetUriListServer.
//! @SYMTestExpectedResults     The Policy data in pre-configuration file should be added to database successfully and Query for the TLD to confirm it.
//! @SYMTestType                CIT
//! @SYMREQ						REQ11517, REQ11519, REQ11521, REQ11665, REQ11666
//! @SYMTestStatus              1. Under Development

PRINT  Executing Deletion of existing database
//! Delete the existing database and forcing to create new database
RUN_UTILS DeleteFile c:\private\10281e17\[20009D70]URIList.dat
PRINT  Executing AppInstall
RUN_TEST_STEP	1000	systemtest_security	AppInstall		c:\testdata\ini\TestWListBListUriSuite.ini	isolated_app_duplicate

PRINT  Executing Query TLD List Type
//! White List type
RUN_TEST_STEP 	100 	TestWListBListUriServer     TestTldPolicyStep 	c:\testdata\ini\testldpolicy.ini  Query_Tld_WhiteList_2
RUN_TEST_STEP 	100 	TestWListBListUriServer     TestTldPolicyStep 	c:\testdata\ini\testldpolicy.ini  Query_Tld_WhiteList_3
RUN_TEST_STEP 	100 	TestWListBListUriServer     TestTldPolicyStep 	c:\testdata\ini\testldpolicy.ini  Query_Tld_WhiteList_4

//! Black List type
RUN_TEST_STEP 	100 	TestWListBListUriServer     TestTldPolicyStep 	c:\testdata\ini\testldpolicy.ini  Query_Tld_BlackList_2
RUN_TEST_STEP 	100 	TestWListBListUriServer     TestTldPolicyStep 	c:\testdata\ini\testldpolicy.ini  Query_Tld_BlackList_3
RUN_TEST_STEP 	100 	TestWListBListUriServer     TestTldPolicyStep 	c:\testdata\ini\testldpolicy.ini  Query_Tld_BlackList_4

PRINT  Executing Query TLD Policy data
//! White List type
RUN_TEST_STEP 	100 	TestWListBListUriServer     TestTldPolicyStep 	c:\testdata\ini\testldpolicy.ini  Query_Tld_Policy_WhiteList_2
RUN_TEST_STEP 	100 	TestWListBListUriServer     TestTldPolicyStep 	c:\testdata\ini\testldpolicy.ini  Query_Tld_Policy_WhiteList_4

//! Black List type
RUN_TEST_STEP 	100 	TestWListBListUriServer     TestTldPolicyStep 	c:\testdata\ini\testldpolicy.ini  Query_Tld_Policy_BlackList_2
RUN_TEST_STEP 	100 	TestWListBListUriServer     TestTldPolicyStep 	c:\testdata\ini\testldpolicy.ini  Query_Tld_Policy_BlackList_5

END_TESTCASE                  IWS-WLBL-TLD-CIT-POS-0001-0001



