//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run all T_MSGS_MESSAGE_CONVERTER_SUITE Tests 
LOAD_SUITE T_MSGS_MESSAGE_CONVERTER_SUITE


RUN_UTILS DeleteFile c:\private\10202be9\persists\10286a26.cre
RUN_UTILS DeleteFile D:\messaging.db
RUN_UTILS DeleteFile e:\messaging.db
RUN_UTILS RmDir D:\private
RUN_UTILS RmDir E:\private
RUN_UTILS RmDir D:\imapresume
RUN_UTILS RmDir D:\smtpresume
RUN_UTILS RmDir D:\popresume
RUN_UTILS RmDir D:\version0version1resume
RUN_UTILS RmDir D:\version1version2resume


RUN_TEST_STEP 1000 T_MSGS_MESSAGE_CONVERTER_SUITE TEFUnit.CTestMessageConverterWaiter.*
RUN_TEST_STEP 1000 T_MSGS_MESSAGE_CONVERTER_SUITE TEFUnit.CTestMessageConverterManager.*

RUN_TEST_STEP 1000 T_MSGS_MESSAGE_CONVERTER_SUITE TEFUnit.CTestVersion1Version2Converter.*
RUN_TEST_STEP 1000 T_MSGS_MESSAGE_CONVERTER_SUITE TEFUnit.CTestConverterDBAdapter.*
RUN_TEST_STEP 1000 T_MSGS_MESSAGE_CONVERTER_SUITE TEFUnit.CTestSmsMessageV1toV2Converter.*



RUN_UTILS DeleteFile c:\private\10202be9\persists\10286a26.cre
RUN_UTILS DeleteFile D:\messaging.db
RUN_UTILS DeleteFile e:\messaging.db
RUN_UTILS RmDir D:\private
RUN_UTILS RmDir E:\private
RUN_UTILS RmDir D:\imapresume
RUN_UTILS RmDir D:\smtpresume
RUN_UTILS RmDir D:\popresume
RUN_UTILS RmDir D:\version0version1resume
RUN_UTILS RmDir D:\version1version2resume
