// Copyright (c) 2004-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// The panic method and panic code declarations
// 
//

/**
 @file 
 @publishedPartner
 @released
*/

#ifndef __RTAPANIC_H__
#define __RTAPANIC_H__

#include <e32base.h>

/** Panic codes generated by the Content Access Framework 
*/
enum TRtaPanics
	{
	ERtaPanicParserInvalidState 					= 1, //< The RTA parser has entered an invalid state
	ERtaPanicImportInvalidState 					= 2 //< The RTA import has entered an invalid state
	};

_LIT(KRtaPanicString,"RTA");

#endif // __RTAPANIC_H__

