//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//! @file

RUN_UTILS DeleteFile c:\messaging.db

LOAD_SUITE	T_MsgCommonServer  	-SharedData
LOAD_SUITE	T_MsgImapServer	-SharedData
LOAD_SUITE	T_MsgSmtpServer	-SharedData


START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0001
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0001
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp
RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini 		0001-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini 		0001-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini 		0001-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini 		0001-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini 		0001-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini 		0001-DeleteAllImapChildren
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini 		0001-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini 		0001-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini 		0001-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini 		0001-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini 		0001-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini 		0001-CreateImap4Folder
RUN_TEST_STEP 	300 	T_MsgImapServer  	CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini 		0001-CheckChildrenCountRemoteInbox1
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini 		0001-DisConnectImap4Server
RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0001




START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0002
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0002
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp
RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0002-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0002-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0002-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0002-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0002-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0002-DeleteAllImapChildren
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0002-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0002-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0002-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0002-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0002-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0002-CreateImap4Folder
//RUN_TEST_STEP 	300 	T_MsgImapServer  	CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0002-CheckChildrenCountRemoteInbox1
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0002-DisConnectImap4Server
RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0002




START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0003
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0003
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp
RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0003-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0003-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0003-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0003-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0003-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0003-DeleteAllImapChildren
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0003-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0003-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0003-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0003-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0003-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0003-CreateImap4Folder
//RUN_TEST_STEP 	300 	T_MsgImapServer  	CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0003-CheckChildrenCountRemoteInbox1
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0003-DoFullImap4Synchronisation
//RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0003-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0003-CreateImap4SubFolder
//RUN_TEST_STEP 	300 	T_MsgImapServer  	CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0003-CheckChildrenCountRemoteInbox1
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0003-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0003




START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0004
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0004
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp
RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0004-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0004-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0004-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0004-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0004-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0004-DeleteAllImapChildren
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0004-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0004-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0004-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0004-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0004-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0004-CreateImap4Folder1
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0004-CreateImap4Folder2
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0004-CreateImap4Folder3
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0004-CreateImap4Folder4
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0004-CreateImap4Folder5
//RUN_TEST_STEP 	300 	T_MsgImapServer  	CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0004-CheckChildrenCountRemoteInbox1
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0004-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0004




START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0005
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0005
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal


PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp
RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0005-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0005-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0005-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0005-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0005-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0005-DeleteAllImapChildren
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0005-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0005-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0005-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0005-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0005-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0005-CreateImap4Folder1
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0005-CreateImap4Folder2
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0005-CreateImap4Folder3
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0005-CreateImap4Folder4
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0005-CreateImap4Folder5
//RUN_TEST_STEP 	300 	T_MsgImapServer  	CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0005-CheckChildrenCountRemoteInbox1
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0005-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0005




START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0006
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0006
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp
RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0006-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0006-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0006-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0006-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0006-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0006-DeleteAllImapChildren
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0006-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0006-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0006-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0006-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0006-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0006-CreateImap4Folder1
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0006-CreateImap4Folder2
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0006-CreateImap4Folder3
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0006-CreateImap4Folder4
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0006-CreateImap4Folder5
//RUN_TEST_STEP 	300 	T_MsgImapServer  	CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0006-CheckChildrenCountRemoteInbox1
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0006-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0006


START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0007
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0007
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0007-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0007-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0007-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0007-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0007-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0007-DeleteAllImapChildren
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0007-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0007-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0007-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0007-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0007-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0007-CreateImap4Folder1
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0007-CreateImap4Folder2
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0007-CreateImap4Folder3
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0007-CreateImap4Folder4
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0007-CreateImap4Folder5
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0007-CreateImap4Folder6
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0007-CreateImap4Folder7
//RUN_TEST_STEP 	300 	T_MsgImapServer  	CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0007-CheckChildrenCountRemoteInbox1
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0007-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0007


START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0008
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0008-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0008-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0008-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0008-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0008-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0008-DeleteAllImapChildren
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0008-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0008-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0008-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0008-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0008-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0008-CreateImap4Folder
//RUN_TEST_STEP 	300 	T_MsgImapServer  	CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0008-CheckChildrenCountRemote
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0008-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0008


START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0009
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0009
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0009-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0009-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0009-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0009-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0009-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0009-DeleteAllImapChildren
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0009-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0009-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0009-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0009-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0009-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0009-CreateImap4Folder
//RUN_TEST_STEP 	300 	T_MsgImapServer  	CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0009-CheckChildrenCountRemote
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0009-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0009


START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0010
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0010
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0010-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0010-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0010-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0010-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0010-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0010-DeleteAllImapChildren
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0010-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0010-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0010-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0010-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0010-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0010-CreateImap4Folder
//RUN_TEST_STEP 	300 	T_MsgImapServer  	CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0010-CheckChildrenCountRemote
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0010-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0010


START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0011
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0011
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0011-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0011-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0011-CreateImapAccount 
RUN_TEST_STEP	300	T_MsgImapServer		ChangeImap4SubAndSyncSettings	c:\msgtest\email\imap\folder\msg-imap-folder1.ini		0011-ChangeImapSettings
RUN_TEST_STEP	300	T_MsgImapServer		ConnectAndSyncImapServer	c:\msgtest\email\imap\folder\msg-imap-folder1.ini		0011-ConnectAndSyncImapServer
RUN_TEST_STEP	300	T_MsgImapServer		InitialiseImap4Account		c:\msgtest\email\imap\folder\msg-imap-folder1.ini		0011-InitialiseImap4Account
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0011-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0011-DeleteAllImapChildren
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0011-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0011-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0011-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0011-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0011-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0011-CreateImap4Folder
RUN_TEST_STEP 	300 	T_MsgImapServer  	CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0011-CheckChildrenCountRemote
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0011-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown
PRINT Execute Completed ################################################

END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0011


START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0012
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0012
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0012-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0012-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0012-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0012-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0012-DoFullImap4Synchronisation
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini 		0012-CreateImap4FolderSendItems
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0012-DeleteAllImapChildren
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0012-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0012-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0012-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0012-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0012-CheckChildrenCountRemoteInbox
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0012-CreateImap4Folder
RUN_TEST_STEP 	300 	T_MsgImapServer  	CheckChildrenCountImap 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0012-CheckChildrenCountRemote
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0012-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0012


START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0013
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0013
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0013-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0013-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0013-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0013-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0013-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0013-DeleteAllImapChildren
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0013-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0013-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0013-DoFullImap4Synchronisation
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0013-CreateImap4Folder
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0013-CreateImap4SubFolder
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0013-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0013


START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0014
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0014
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0014-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0014-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0014-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0014-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0014-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0014-DeleteAllImapChildren
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0014-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0014-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0014-DoFullImap4Synchronisation
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0014-CreateImap4Folder
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0014-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0014


START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0015
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0015
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0015-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0015-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0015-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0015-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0015-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0015-DeleteAllImapChildren
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0015-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0015-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0015-DoFullImap4Synchronisation
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0015-CreateImap4Folder
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0015-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown
PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0015


START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0016
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0016
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0016-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0016-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0016-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0016-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0016-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0016-DeleteAllImapChildren
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0016-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0016-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0016-DoFullImap4Synchronisation
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0016-CreateImap4Folder
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0016-DoFullImap4Synchronisation
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0016-CreateImap4SubFolder
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0016-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0016


START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0017
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0017
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0017-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0017-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0017-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0017-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0017-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0017-DeleteAllImapChildren
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0017-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0017-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0017-DoFullImap4Synchronisation
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0017-CreateImap4Folder1
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0017-CreateImap4Folder2
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0017-CreateImap4Folder3
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0017-CreateImap4Folder4
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0017-CreateImap4Folder5
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0017-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0017


START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0018
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0018
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0018-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0018-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0018-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0018-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0018-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0018-DeleteAllImapChildren
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0018-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0018-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0018-DoFullImap4Synchronisation
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0018-CreateImap4Folder1
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0018-CreateImap4Folder2
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0018-CreateImap4Folder3
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0018-CreateImap4Folder4
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0018-CreateImap4Folder5
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0018-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0018


START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0019
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0019
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0019-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0019-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0019-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0019-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0019-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0019-DeleteAllImapChildren
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0019-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0019-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0019-DoFullImap4Synchronisation
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0019-CreateImap4Folder1
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0019-CreateImap4Folder2
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0019-CreateImap4Folder3
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0019-CreateImap4Folder4
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0019-CreateImap4Folder5
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0019-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0019


START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0020
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0020
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0020-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0020-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0020-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0020-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0020-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0020-DeleteAllImapChildren
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0020-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0020-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0020-DoFullImap4Synchronisation
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0020-CreateImap4Folder1
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0020-CreateImap4Folder2
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0020-CreateImap4Folder3
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0020-CreateImap4Folder4
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0020-CreateImap4Folder5
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0020-CreateImap4Folder6
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0020-CreateImap4Folder7
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0020-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0020


START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0021
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0021-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0021-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0021-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0021-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0021-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0021-DeleteAllImapChildren
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0021-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0021-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0021-DoFullImap4Synchronisation
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0021-CreateImap4Folder
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0021-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0021


START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0022
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0022
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp
RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0022-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0022-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0022-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0022-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0022-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0022-DeleteAllImapChildren
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0022-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0022-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0022-DoFullImap4Synchronisation
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0022-CreateImap4Folder
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0022-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0022


// Testcase id :MSG-IMAP-CREATE-FOLDER-0023 has been commented out
// this is due it causing this script to hang and utimately crash
// a hardware board during an arm run
// the defect number associated with this is: defect 100421

START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0023
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0023
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal


PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0023-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0023-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0023-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0023-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0023-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0023-DeleteAllImapChildren
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0023-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0023-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0023-DoFullImap4Synchronisation
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0023-CreateImap4Folder
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0023-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0023


START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0024
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0024
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0024-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0024-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0024-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0024-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0024-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0024-DeleteAllImapChildren
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0024-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0024-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0024-DoFullImap4Synchronisation
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0024-CreateImap4Folder
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0024-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0024


START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0025
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0025
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0025-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0025-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0025-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0025-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0025-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0025-DeleteAllImapChildren
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0025-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0025-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0025-DoFullImap4Synchronisation
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0025-CreateImap4Folder
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0025-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0025


START_TESTCASE	MSG-IMAP-CREATE-FOLDER-0026
//!	@SYMTestCaseID			MSG-IMAP-CREATE-FOLDER-0026
//!	@SYMTestCaseDesc		This test script creates an IMAP account and a message
//!					from the RFC822 file and sends the message to the same account.
//!					Downloads the mails with IMAP4 KIMAP4MTMConnectAndPopulateAllMailAndStayOnline 
//!					command and Compares the received messages with sent messages based on the 
//!					Download limits set.It then checks the count of the messages based on the various flags set.
//!	@SYMTestPriority		Critical
//!   	@SYMTestType			CIT
//!  	@SYMTestStatus			Implemented   
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions			Initialises the RAS connection
//!					Resets the message store to clean up the central repository
//!					Creates an IMAP account by reading the settings from the file mentioned
//!					thus setting the IMAP and SMTP service settings
//!					Connects to the IMAP server and performs full sync with IMAP4 server.
//!					Connects to the IMAP server and deletes all mails in the Inbox on the server.
//!					Disconnect from the IMAP Service.
//!
//!
//!	@SYMTestExpectedResults		EPass,
//!	@SYMAuthor			Rajat Bal

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer  	InitNtRas			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0026-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer  	ResetMessageStore		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0026-ResetMessageStore
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImapAccount 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0026-CreateImapAccount 
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0026-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0026-DoFullImap4Synchronisation
RUN_TEST_STEP  	300 	T_MsgImapServer		DeleteAllImapChildren 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0026-DeleteAllImapChildren
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0026-DisConnectImap4Server
PRINT Setup Completed
PRINT Execute begins
RUN_TEST_STEP 	300 	T_MsgImapServer		ConnectImap4Server		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0026-ConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0026-DoFullImap4Synchronisation
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0026-CreateImap4Folder
RUN_TEST_STEP 	300 	T_MsgImapServer		CreateImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0026-CreateImap4SubFolder
RUN_TEST_STEP 	300 	T_MsgImapServer		DisConnectImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  		0026-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-CREATE-FOLDER-0026


START_TESTCASE	MSG-IMAP-DeleteFolder-0001
//!	@SYMTestCaseID				MSG-IMAP-DeleteFolder-0001
//!	@SYMTestCaseDesc			Negative: Delete remote INBOX (-ve)
//!	@SYMTestPriority			Critical
//!	@SYMTestType				CIT
//! @SYMREQ						5569 (Delete Folder)
//! @SYMPREQ					1160
//!	@SYMTestStatus				Implemented
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions				1.	Reset Message Store and Central Repository to default state.
//!								2.	Create IMAP account in Central Repository using settings from a configuration file.
//!								3.	Connect to IMAP4 service using Account Settings and initialise account on remote IMAP4 server to default clean state.
//!								4.	Create multiple messages from file and send using SMTP to remote INBOX.
//!								5.	Delete the remote INBOX folder.
//!								6.	Check for appropriate error message after attempting step 5 and also check that all messages in the remote INBOX were deleted first.
//!								7.	Disconnect from IMAP4 service.
//!
//!	@SYMTestExpectedResults		NO - delete failure: can't delete mailbox with that name (See step 6)
//!	@SYMAuthor					Sandip Ahluwalia


PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer	InitNtRas						c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer	ResetMessageStore				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-ResetMessageStore
RUN_TEST_STEP	300	T_MsgImapServer		CreateImapAccount				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-CreateImapAccount
RUN_TEST_STEP	300	T_MsgImapServer		ChangeImap4SubAndSyncSettings	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-ChangeImapSettings
RUN_TEST_STEP	300	T_MsgImapServer		ConnectAndSyncImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-ConnectAndSyncImapServer
RUN_TEST_STEP	300	T_MsgImapServer		InitialiseImap4Account			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-InitialiseImap4Account
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-DoFullImap4Synchronisation
RUN_TEST_STEP	300	T_MsgImapServer		CheckChildrenCountImap			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-CheckChildrenCountRemoteInbox
RUN_TEST_STEP	300	T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-DisConnectImap4Server
PRINT Setup Completed ##################################################
PRINT Sub-Setup Begins #################################################
//Following set of test steps create multiple messages from file and send it using SMTP to remote INBOX
RUN_TEST_STEP 	300 T_MsgImapServer		SetImap4FullDownloadLimits 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-SetImap4FullDownloadLimits
//Sending first message
RUN_TEST_STEP 	300 T_MsgSmtpServer		CreateSmtpMessageFromEmailFile 	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-CreateSmtpMessageFromEmailFile1
RUN_TEST_STEP 	300 T_MsgCommonServer  	CheckChildrenCount 				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-CheckChildrenCountOutbox
RUN_TEST_STEP 	300 T_MsgSmtpServer		SendSmtpMessage 				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-SendSmtpMessage1
RUN_TEST_STEP	300	T_MsgImapServer		ConnectAndSyncImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-ConnectAndSyncImapServer
RUN_TEST_STEP 	300 T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-DisConnectImap4Server
//Sending second message
RUN_TEST_STEP 	300 T_MsgSmtpServer		CreateSmtpMessageFromEmailFile 	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-CreateSmtpMessageFromEmailFile2
RUN_TEST_STEP 	300 T_MsgCommonServer  	CheckChildrenCount 				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-CheckChildrenCountOutbox
RUN_TEST_STEP 	300 T_MsgSmtpServer		SendSmtpMessage 				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-SendSmtpMessage2
RUN_TEST_STEP	300	T_MsgImapServer		ConnectAndSyncImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-ConnectAndSyncImapServer
RUN_TEST_STEP 	300 T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-DisConnectImap4Server
//ConnectAndPopulateAllMailAndStayOnline
RUN_TEST_STEP 	300 T_MsgImapServer		ImapInvokeAsyncFunction      	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-ImapInvokeAsyncFunction
RUN_TEST_STEP  	300 T_MsgImapServer		CheckChildrenCountImap 			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-CheckChildrenCountRemoteInbox1
RUN_TEST_STEP 	300 T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-DisConnectImap4Server
PRINT Sub-Setup Completed ##############################################
PRINT Execute Begins ###################################################
RUN_TEST_STEP	300	T_MsgImapServer		ConnectAndSyncImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-ConnectAndSyncImapServer
RUN_TEST_STEP	!Error=-212		300	T_MsgImapServer		DeleteImap4Folder	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-DeleteFolder
RUN_TEST_STEP	300	T_MsgImapServer		CheckChildrenCountImap			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-CheckChildrenCountRemoteInbox
RUN_TEST_STEP	300	T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0027-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-DeleteFolder-0001


START_TESTCASE	MSG-IMAP-DeleteFolder-0002
//!	@SYMTestCaseID				MSG-IMAP-DeleteFolder-0002
//!	@SYMTestCaseDesc			Negative: Delete Non-existing remote mailbox (-ve)
//!	@SYMTestPriority			Critical
//!	@SYMTestType				CIT
//! @SYMREQ						5569 (Delete Folder)
//! @SYMPREQ					1160
//!	@SYMTestStatus				Implemented
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions				1.	Reset Message Store and Central Repository to default state.
//!								2.	Create 2 IMAP accounts in Central Repository using same settings from a configuration file.
//!								3.	Connect to IMAP4 service using Account Settings via one of the accounts created in step 2 (called for example AccountB) 
//!									and initialise account on remote IMAP4 server to default clean state.
//!								4.	Create remote folder in AccountB and check for successful creation.
//!								5.	Disconnect from IMAP4 service using AccountB.
//!								6.	Connect to IMAP4 service using Account Settings via the other account not used step 3 (called for example AccountA).
//!								7.	Delete the remote folder created in step 4.
//!								8.	Disconnect from IMAP4 service using AccountA.
//!								9.	Connect without synchronising to IMAP4 service using AccountB.
//!								10.	Delete the remote folder created in step 4 that does not exist on the IMAP4 server, but still should exist in the remote mirrored message store.
//!								11.	Check for appropriate error message after attempting step 10 and for the folder in the remote mirrored message store now being deleted.
//!								12.	Disconnect from IMAP4 service using AccountB.
//!
//!	@SYMTestExpectedResults		NO - delete failure: can't delete mailbox with that name and deletion of folder in the remote mirrored message store (See step 11).
//!	@SYMAuthor					Sandip Ahluwalia

PRINT Setup Begins #################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer	InitNtRas						c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer	ResetMessageStore				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-ResetMessageStore
//Account A creation...
RUN_TEST_STEP	300	T_MsgImapServer		CreateImapAccount				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-CreateImapAccount_A
RUN_TEST_STEP	300	T_MsgImapServer		ChangeImap4SubAndSyncSettings	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-ChangeImapSettings_A
RUN_TEST_STEP	300	T_MsgImapServer		ConnectAndSyncImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-ConnectAndSyncImapServer_A
RUN_TEST_STEP	300	T_MsgImapServer		InitialiseImap4Account			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-InitialiseImap4Account_A
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-DoFullImap4Synchronisation_A
RUN_TEST_STEP	300	T_MsgImapServer		CheckChildrenCountImap			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-CheckChildrenCountRemoteInbox_A
RUN_TEST_STEP	300	T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-DisConnectImap4Server_A
PRINT ##################################
//Account B creation...
RUN_TEST_STEP	300	T_MsgImapServer		CreateImapAccount				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-CreateImapAccount_B
RUN_TEST_STEP	300	T_MsgImapServer		ConnectAndSyncImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-ConnectAndSyncImapServer_B
RUN_TEST_STEP	300	T_MsgImapServer		CheckChildrenCountImap			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-CheckChildrenCountRemoteInbox_B
RUN_TEST_STEP	300	T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-DisConnectImap4Server_B
PRINT Setup Completed ##############################################
PRINT Execute Begins ###############################################
//Account B execution...
RUN_TEST_STEP	300	T_MsgImapServer		ConnectAndSyncImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-ConnectAndSyncImapServer_B
RUN_TEST_STEP	300	T_MsgImapServer		CreateImap4Folder				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-CreateImap4Folder_B
RUN_TEST_STEP	300	T_MsgImapServer		FindEntryByName					c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-FindEntryByName_B
RUN_TEST_STEP	300	T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-DisConnectImap4Server_B
PRINT ##################################
//Account A execution...
RUN_TEST_STEP	300	T_MsgImapServer		ConnectAndSyncImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-ConnectAndSyncImapServer_A
RUN_TEST_STEP 	300	T_MsgImapServer		DeleteImap4Folder				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-DeleteImap4Folder_A
RUN_TEST_STEP	300	T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-DisConnectImap4Server_A
PRINT ##################################
//Account B execution...
RUN_TEST_STEP	300	T_MsgImapServer		ConnectImap4Server				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-ConnectImap4Server_B
RUN_TEST_STEP	!Error=-212 300	T_MsgImapServer		DeleteImap4Folder		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-DeleteImap4Folder_B
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-DoFullImap4Synchronisation_B
RUN_TEST_STEP	!Error=-1	300	T_MsgImapServer		FindEntryByName			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-FindEntryByName_B
RUN_TEST_STEP	300	T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0028-DisConnectImap4Server_B

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-DeleteFolder-0002


START_TESTCASE	MSG-IMAP-DeleteFolder-0003
//!	@SYMTestCaseID				MSG-IMAP-DeleteFolder-0003
//!	@SYMTestCaseDesc			Positive: Delete remote Root-level selectable mailbox (+ve)
//!	@SYMTestPriority			Critical
//!	@SYMTestType				CIT
//! @SYMREQ						5569 (Delete Folder)
//! @SYMPREQ					1160
//!	@SYMTestStatus				Implemented
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions				1.	Reset Message Store and Central Repository to default state.
//!								2.	Create IMAP account in Central Repository using settings from a configuration file.
//!								3.	Connect to IMAP4 service using Account Settings and initialise account on remote IMAP4 server to default clean state.
//!								4.	Create remote root-level folder with multiple messages.
//!								5.	Delete the folder created in step 4.
//!								6.	Check if the folder created in step 4 is removed with all its contents deleted.
//!								7.	Disconnect from IMAP4 service.
//!
//!	@SYMTestExpectedResults		OK - delete completed (See step 6)
//!	@SYMAuthor					Sandip Ahluwalia

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer	InitNtRas						c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer	ResetMessageStore				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-ResetMessageStore
RUN_TEST_STEP	300	T_MsgImapServer		CreateImapAccount				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-CreateImapAccount
RUN_TEST_STEP	300	T_MsgImapServer		ChangeImap4SubAndSyncSettings	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-ChangeImapSettings
RUN_TEST_STEP	300	T_MsgImapServer		ConnectAndSyncImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-ConnectAndSyncImapServer
RUN_TEST_STEP	300	T_MsgImapServer		InitialiseImap4Account			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-InitialiseImap4Account
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-DoFullImap4Synchronisation
RUN_TEST_STEP	300	T_MsgImapServer		CheckChildrenCountImap			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-CheckChildrenCountRemoteInbox
RUN_TEST_STEP	300	T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-DisConnectImap4Server
PRINT Setup Completed ##################################################
PRINT Sub-Setup Begins #################################################
//Following set of test steps create multiple messages from file and send it using SMTP to remote INBOX
RUN_TEST_STEP 	300 T_MsgImapServer		SetImap4FullDownloadLimits 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-SetImap4FullDownloadLimits
//Sending first message
RUN_TEST_STEP 	300 T_MsgSmtpServer		CreateSmtpMessageFromEmailFile 	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-CreateSmtpMessageFromEmailFile1
RUN_TEST_STEP 	300 T_MsgCommonServer  	CheckChildrenCount 				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-CheckChildrenCountOutbox
RUN_TEST_STEP 	300 T_MsgSmtpServer		SendSmtpMessage 				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-SendSmtpMessage1
RUN_TEST_STEP	300	T_MsgImapServer		ConnectAndSyncImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-ConnectAndSyncImapServer
RUN_TEST_STEP 	300 T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-DisConnectImap4Server
//Sending second message
RUN_TEST_STEP 	300 T_MsgSmtpServer		CreateSmtpMessageFromEmailFile 	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-CreateSmtpMessageFromEmailFile2
RUN_TEST_STEP 	300 T_MsgCommonServer  	CheckChildrenCount 				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-CheckChildrenCountOutbox
RUN_TEST_STEP 	300 T_MsgSmtpServer		SendSmtpMessage 				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-SendSmtpMessage2
RUN_TEST_STEP	300	T_MsgImapServer		ConnectAndSyncImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-ConnectAndSyncImapServer
RUN_TEST_STEP 	300 T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-DisConnectImap4Server
//ConnectAndPopulateAllMailAndStayOnline
RUN_TEST_STEP 	300 T_MsgImapServer		ImapInvokeAsyncFunction      	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-ImapInvokeAsyncFunction
RUN_TEST_STEP  	300 T_MsgImapServer		CheckChildrenCountImap 			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-CheckChildrenCountRemoteInbox1
RUN_TEST_STEP 	300 T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-DisConnectImap4Server
PRINT Sub-Setup Completed ##############################################
PRINT Execute Begins ###################################################
RUN_TEST_STEP	300	T_MsgImapServer		ConnectAndSyncImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-ConnectAndSyncImapServer
RUN_TEST_STEP	300	T_MsgImapServer		CreateImap4Folder				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-CreateFolder
RUN_TEST_STEP	300	T_MsgImapServer		FindEntryByName					c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-FindEntryByName
RUN_TEST_STEP 	300 T_MsgImapServer		CopyImapSelectionRemote			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-CopyImapSelectionRemote
RUN_TEST_STEP	300	T_MsgImapServer		CheckChildrenCountImap			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-CheckChildrenCountImap
RUN_TEST_STEP	300	T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-DisConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		ConnectAndSyncImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-ConnectAndSyncImapServer
RUN_TEST_STEP	300	T_MsgImapServer		DeleteImap4Folder				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-DeleteFolder
RUN_TEST_STEP	!Error=-1	300	T_MsgImapServer		FindEntryByName			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-FindEntryByName
RUN_TEST_STEP	300	T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0029-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-DeleteFolder-0003


START_TESTCASE	MSG-IMAP-DeleteFolder-0004
//!	@SYMTestCaseID				MSG-IMAP-DeleteFolder-0004
//!	@SYMTestCaseDesc			Positive/Negative: Delete remote Root-level selectable mailbox with a sub folder (+ve/-ve)
//!	@SYMTestPriority			Critical
//!	@SYMTestType				CIT
//! @SYMREQ						5569 (Delete Folder)
//! @SYMPREQ					1160
//!	@SYMTestStatus				Implemented
//!	@SYMTestCaseDependencies	requires ced -i c:\ced_default_ras.cfg to set comms.
//!	@SYMTestActions				1.	Reset Message Store and Central Repository to default state.
//!								2.	Create IMAP account in Central Repository using settings from a configuration file.
//!								3.	Connect to IMAP4 service using Account Settings and initialise account on remote IMAP4 server to default clean state.
//!								4.	Create remote root-level folder with multiple messages.
//!								5.	Create sub folder under the folder created in step 4 with multiple messages. 
//!								6.	Delete the folder created in step 4.
//!								7.	If IMAP4 server responds OK/NO then check if the folder created in step 4 still exists, but all its contents deleted 
//!									and that the sub folder with all its messages still exists.
//!								8.	Disconnect from IMAP4 service.
//!								
//!	@SYMTestExpectedResults		OK - delete completed or NO - delete failure: can't delete mailbox with that name (See step 7)
//!	@SYMAuthor					Sandip Ahluwalia

PRINT Setup Begins #####################################################

RUN_TEST_STEP	300	T_MsgCommonServer  	StartUp
RUN_TEST_STEP	300	T_MsgImapServer	StartUp
RUN_TEST_STEP	300	T_MsgSmtpServer	StartUp

RUN_TEST_STEP	300	T_MsgCommonServer	InitNtRas						c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-InitNtRas
RUN_TEST_STEP	300	T_MsgCommonServer	ResetMessageStore				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-ResetMessageStore
RUN_TEST_STEP	300	T_MsgImapServer		CreateImapAccount				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-CreateImapAccount
RUN_TEST_STEP	300	T_MsgImapServer		ChangeImap4SubAndSyncSettings	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-ChangeImapSettings1
RUN_TEST_STEP	300	T_MsgImapServer		ConnectAndSyncImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-ConnectAndSyncImapServer
RUN_TEST_STEP	300	T_MsgImapServer		InitialiseImap4Account			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-InitialiseImap4Account
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-DoFullImap4Synchronisation
RUN_TEST_STEP	300	T_MsgImapServer		CheckChildrenCountImap			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-CheckChildrenCountRemoteInbox
RUN_TEST_STEP	300	T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-DisConnectImap4Server
PRINT Setup Completed ##################################################
PRINT Sub-Setup Begins #################################################
//Following set of test steps create multiple messages from file and send it using SMTP to remote INBOX
RUN_TEST_STEP 	300 T_MsgImapServer		SetImap4FullDownloadLimits 		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-SetImap4FullDownloadLimits
//Sending first message
RUN_TEST_STEP 	300 T_MsgSmtpServer		CreateSmtpMessageFromEmailFile 	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-CreateSmtpMessageFromEmailFile1
RUN_TEST_STEP 	300 T_MsgCommonServer  	CheckChildrenCount 				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-CheckChildrenCountOutbox
RUN_TEST_STEP 	300 T_MsgSmtpServer		SendSmtpMessage 				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-SendSmtpMessage1
RUN_TEST_STEP	300	T_MsgImapServer		ConnectAndSyncImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-ConnectAndSyncImapServer
RUN_TEST_STEP 	300 T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-DisConnectImap4Server
//Sending second message
RUN_TEST_STEP 	300 T_MsgSmtpServer		CreateSmtpMessageFromEmailFile 	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-CreateSmtpMessageFromEmailFile2
RUN_TEST_STEP 	300 T_MsgCommonServer  	CheckChildrenCount 				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-CheckChildrenCountOutbox
RUN_TEST_STEP 	300 T_MsgSmtpServer		SendSmtpMessage 				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-SendSmtpMessage2
RUN_TEST_STEP	300	T_MsgImapServer		ConnectAndSyncImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-ConnectAndSyncImapServer
RUN_TEST_STEP 	300 T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-DisConnectImap4Server
//ConnectAndPopulateAllMailAndStayOnline
RUN_TEST_STEP 	300 T_MsgImapServer		ImapInvokeAsyncFunction      	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-ImapInvokeAsyncFunction
RUN_TEST_STEP  	300 T_MsgImapServer		CheckChildrenCountImap 			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-CheckChildrenCountRemoteInbox1
RUN_TEST_STEP 	300 T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-DisConnectImap4Server
PRINT Sub-Setup Completed ##############################################
PRINT Execute Begins ###################################################
RUN_TEST_STEP	300	T_MsgImapServer		ConnectAndSyncImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-ConnectAndSyncImapServer
RUN_TEST_STEP	300	T_MsgImapServer		CreateImap4Folder				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-CreateFolder1
RUN_TEST_STEP	300	T_MsgImapServer		FindEntryByName					c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-FindEntryByName1
RUN_TEST_STEP 	300 T_MsgImapServer		CopyImapSelectionRemote			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-CopyImapSelectionRemote1
RUN_TEST_STEP	300	T_MsgImapServer		CheckChildrenCountImap			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-CheckChildrenCountTargetFolder1
RUN_TEST_STEP	300	T_MsgImapServer		CreateImap4Folder				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-CreateFolder2
RUN_TEST_STEP	300	T_MsgImapServer		FindEntryByName					c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-FindEntryByName2
RUN_TEST_STEP 	300 T_MsgImapServer		CopyImapSelectionRemote			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-CopyImapSelectionRemote2
RUN_TEST_STEP	300	T_MsgImapServer		CheckChildrenCountImap			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-CheckChildrenCountTargetFolder2
RUN_TEST_STEP	300	T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-DisConnectImap4Server
RUN_TEST_STEP	300	T_MsgImapServer		ConnectAndSyncImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-ConnectAndSyncImapServer
RUN_TEST_STEP	300	T_MsgImapServer		DeleteImap4Folder				c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-DeleteFolder
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-DoFullImap4Synchronisation
RUN_TEST_STEP	300	T_MsgImapServer		FindEntryByName					c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-FindEntryByName1
RUN_TEST_STEP	300	T_MsgImapServer		FindEntryByName					c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-FindEntryByName2
RUN_TEST_STEP	300	T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-DisConnectImap4Server
// Need to subscribe to sub folder for its contents to be synchronised!
RUN_TEST_STEP	300	T_MsgImapServer		ChangeImap4SubAndSyncSettings	c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-ChangeImapSettings2
RUN_TEST_STEP	300	T_MsgImapServer		ConnectAndSyncImapServer		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-ConnectAndSyncImapServer
RUN_TEST_STEP	300	T_MsgImapServer		SubscribeImap4Folder			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-SubscribeImap4Folder1
RUN_TEST_STEP	300	T_MsgImapServer		SubscribeImap4Folder			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-SubscribeImap4Folder2
RUN_TEST_STEP	300	T_MsgImapServer		DoFullImap4Synchronisation		c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-DoFullImap4Synchronisation
RUN_TEST_STEP	300	T_MsgImapServer		CheckChildrenCountImap			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-CheckChildrenCountTargetFolder1a
RUN_TEST_STEP	300	T_MsgImapServer		CheckChildrenCountImap			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-CheckChildrenCountTargetFolder2
RUN_TEST_STEP	300	T_MsgImapServer		DisConnectImapServer			c:\msgtest\email\imap\folder\msg-imap-folder1.ini  	0030-DisConnectImap4Server

RUN_TEST_STEP	300	T_MsgCommonServer	ShutDown
RUN_TEST_STEP	300	T_MsgImapServer		ShutDown
RUN_TEST_STEP	300	T_MsgSmtpServer		ShutDown

PRINT Execute Completed ################################################
END_TESTCASE	MSG-IMAP-DeleteFolder-0004



