// Copyright (c) 2002-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// $Header$
// GT0149 Applications Protocol Integration Test Harness
// blank application
// created by: mark j davey
// mjd systems solutions ltd
// mark@mjdss.com
// Error Code and Other Defines
// by mjd
// 
//

#ifndef __ERRCODES_H__
#define __ERRCODES_H__

//----------------------------------------------------------------------------
//  Error Codes generated by Test Harness Application

enum
  {
  KErrScriptNameNotFound,
	KErrCommandFlagNotFound,
	KErrCommandFlagNotDefined,
	KErrUnabletoCreateTestEngine,
	KSysCmdParameter,
	KAppendParameter,
  KErrMaxErrorCode
  } THA_ERROR_CODES;

//----------------------------------------------------------------------------
// Defined active object priorities

const TInt KActivePriority = CActive::EPriorityStandard;
//const TInt KTransactionActivePriority = KActivePriority + 1;

//----------------------------------------------------------------------------

#endif

//----------------------------------------------------------------------------
//	End of File
//----------------------------------------------------------------------------
