// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// Autogenerated from HtmlTagsTable.st by the stringtable tool - Do not edit
// 
//

#ifndef STRINGTABLE_HtmlTagsStringTable
#define STRINGTABLE_HtmlTagsStringTable

#include "stringpool.h"

struct TStringTable;

/** A String table */
class HtmlTagsStringTable 
	{
public:
	enum TStrings
		{
		/** body */
		EBody,
		/** colgroup */
		EColGroup,
		/** dd */
		EDD,
		/** dt */
		EDt,
		/** head */
		EHead,
		/** html */
		EHtml,
		/** li */
		ELi,
		/** option */
		EOption,
		/** p */
		EP,
		/** tbody */
		ETBody,
		/** td */
		ETD,
		/** tfoot */
		ETFoot,
		/** th */
		ETH,
		/** thead */
		ETHead,
		/** tr */
		ETr,
		/** area */
		EArea, // forbidden tags starts here...
		/** base */
		EBase,
		/** basefont */
		EBaseFont,
		/** br */
		EBr,
		/** col */
		ECol,
		/** frame */
		EFrame,
		/** hr */
		EHr,
		/** img */
		EImg,
		/** input */
		EInput,
		/** isindex */
		EIsIndex,
		/** link */
		ELink,
		/** meta */
		EMeta,
		/** param */
		EParam
		};
	static const TStringTable Table;	
	};

#endif // STRINGTABLE_HtmlTagsStringTable

