#
# Copyright (c) 2006-2009 Nokia Corporation and/or its subsidiary(-ies).
# All rights reserved.
# This component and the accompanying materials are made available
# under the terms of "Eclipse Public License v1.0"
# which accompanies this distribution, and is available
# at the URL "http://www.eclipse.org/legal/epl-v10.html".
#
# Initial Contributors:
# Nokia Corporation - initial contribution.
#
# Contributors:
#
# Description:
#
stringtable Sl1_0StringDict00AttributeTable
# //////////////////////////////////////////////////////////////////////
!// Element names
!// CodePage 00
EAction1 		action
EAction2 		action
EAction3 		action
EHref1 			href
EHref2 			href
EHref3 			href
EHref4 			href
EHref5 			href